name: up
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52758
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#e4aba4'
    - '#7f9ea3'
    - '#1a191f'
    - '#a05750'
  brandStrength: 0.2011044346727431
  lightness: 0.7244898
  saturation: 0.875
  rhythmicContrast: 0.1143931
purpose: []
